# Generated by Django 5.0.7 on 2024-08-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField()),
                ('payment_number', models.CharField(max_length=10)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
