# Generated by Django 5.0.7 on 2024-07-30 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=10)),
                ('father_name', models.CharField(max_length=45)),
                ('feasibility_phone', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=10)),
                ('id_number', models.CharField(max_length=30)),
                ('birth_certificate_number', models.CharField(max_length=30)),
                ('ownership_type', models.CharField(max_length=10)),
                ('line_owner_name', models.CharField(max_length=45)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('usage_type', models.CharField(max_length=20)),
                ('educational_degree', models.CharField(max_length=45)),
                ('subscriber_type', models.CharField(max_length=20)),
                ('customer_group', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('selection_date', models.DateField()),
                ('last_street', models.CharField(max_length=45)),
                ('plate_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuals',
                'db_table': 'individual',
            },
        ),
        migrations.CreateModel(
            name='Legal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('representative_name', models.CharField(max_length=20)),
                ('representative_surname', models.CharField(max_length=40)),
                ('representative_nationality', models.CharField(max_length=15)),
                ('id_type', models.CharField(max_length=30)),
                ('representative_birth_certificate_number', models.CharField(max_length=45)),
                ('representative_id_number', models.CharField(max_length=45)),
                ('feasibility_phone', models.CharField(max_length=20)),
                ('ownership_type', models.CharField(max_length=10)),
                ('company_national_id', models.CharField(max_length=20)),
                ('registration_number', models.CharField(max_length=20)),
                ('economic_code', models.CharField(max_length=20)),
                ('company_type', models.CharField(max_length=10)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=45)),
                ('postal_code', models.CharField(max_length=30)),
                ('usage_type', models.CharField(max_length=20)),
                ('representative_educational_degree', models.CharField(max_length=45)),
                ('subscriber_type', models.CharField(max_length=20)),
                ('customer_group', models.CharField(max_length=20)),
                ('establishment_date', models.CharField(max_length=10)),
                ('representative_birth_date', models.CharField(max_length=10)),
                ('plate_number', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
                'db_table': 'legal',
            },
        ),
    ]
