# Generated by Django 5.0.7 on 2024-07-30 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legal',
            options={'verbose_name': 'مشتری حقوقی', 'verbose_name_plural': 'مشتریان حقوقی'},
        ),
        migrations.AlterField(
            model_name='legal',
            name='company_name',
            field=models.CharField(max_length=50, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='company_national_id',
            field=models.CharField(max_length=20, verbose_name='شناسه ملی شرکت'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='company_type',
            field=models.CharField(max_length=10, verbose_name='نوع شرکت'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='customer_group',
            field=models.CharField(max_length=20, verbose_name='گروه مشتری'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='economic_code',
            field=models.CharField(max_length=20, verbose_name='کد اقتصادی'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='email',
            field=models.EmailField(max_length=45, verbose_name='پست الکترونیک'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='establishment_date',
            field=models.CharField(max_length=10, verbose_name='تاریخ تاسیس'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='feasibility_phone',
            field=models.CharField(max_length=20, verbose_name='تلفن امکان سنجی'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='id_type',
            field=models.CharField(max_length=30, verbose_name='نوع شناسه هویتی'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='mobile_phone',
            field=models.CharField(max_length=20, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='ownership_type',
            field=models.CharField(max_length=10, verbose_name='نوع مالکیت'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='plate_number',
            field=models.CharField(max_length=5, verbose_name='شماره پلاک'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='postal_code',
            field=models.CharField(max_length=30, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='registration_number',
            field=models.CharField(max_length=20, verbose_name='شماره ثبت'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='representative_birth_certificate_number',
            field=models.CharField(max_length=45, verbose_name='شماره شناسنامه نماینده'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='representative_birth_date',
            field=models.CharField(max_length=10, verbose_name='تاریخ تولد نماینده/مدیرعامل'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='representative_educational_degree',
            field=models.CharField(max_length=45, verbose_name='مدرک تحصیلی نماینده/مدیرعامل'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='representative_id_number',
            field=models.CharField(max_length=45, verbose_name='شماره شناسه هویتی نماینده'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='representative_name',
            field=models.CharField(max_length=20, verbose_name='نام نماینده/مدیرعامل'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='representative_nationality',
            field=models.CharField(max_length=15, verbose_name='ملیت نماینده/مدیرعامل'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='representative_surname',
            field=models.CharField(max_length=40, verbose_name='نام خانوادگی نماینده/مدیرعامل'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='subscriber_type',
            field=models.CharField(max_length=20, verbose_name='نوع مشترک'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='usage_type',
            field=models.CharField(max_length=20, verbose_name='نوع کاربری'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterModelTable(
            name='legal',
            table=None,
        ),
    ]
