# Generated by Django 5.0.7 on 2024-07-30 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_legal_options_alter_legal_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='individual',
            options={'verbose_name': 'فرد', 'verbose_name_plural': 'افراد'},
        ),
        migrations.AlterField(
            model_name='individual',
            name='address',
            field=models.CharField(max_length=50, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='birth_certificate_number',
            field=models.CharField(max_length=30, verbose_name='شماره شناسنامه'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='birth_date',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='customer_group',
            field=models.CharField(max_length=20, verbose_name='گروه مشتری'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='educational_degree',
            field=models.CharField(max_length=45, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='پست الکترونیک'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='father_name',
            field=models.CharField(max_length=45, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='feasibility_phone',
            field=models.CharField(max_length=20, verbose_name='تلفن امکان سنجی'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='id_number',
            field=models.CharField(max_length=30, verbose_name='شماره شناسه هویتی'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='last_street',
            field=models.CharField(max_length=45, verbose_name='معبر آخر'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='line_owner_name',
            field=models.CharField(max_length=45, verbose_name='نام مالک خط'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='mobile_phone',
            field=models.CharField(max_length=20, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=45, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='nationality',
            field=models.CharField(max_length=10, verbose_name='ملیت'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='ownership_type',
            field=models.CharField(max_length=10, verbose_name='نوع مالکیت'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='plate_number',
            field=models.CharField(max_length=10, verbose_name='شماره پلاک'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='postal_code',
            field=models.CharField(max_length=30, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='selection_date',
            field=models.DateField(verbose_name='انتخاب تاریخ'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='subscriber_type',
            field=models.CharField(max_length=20, verbose_name='نوع مشترک'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='surname',
            field=models.CharField(max_length=45, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='usage_type',
            field=models.CharField(max_length=20, verbose_name='نوع کاربری'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterModelTable(
            name='legal',
            table='legal',
        ),
    ]
